export const US_BANKS = [
  "Ally Bank",
  "American Express National Bank",
  "Bank of America",
  "Bank of the West",
  "BMO Harris Bank",
  "Capital One",
  "Charles Schwab Bank",
  "Chime",
  "Citibank",
  "Citizens Bank",
  "Comerica Bank",
  "Discover Bank",
  "Fifth Third Bank",
  "First Citizens Bank",
  "First Horizon Bank",
  "Frost Bank",
  "Huntington National Bank",
  "JPMorgan Chase Bank",
  "KeyBank",
  "M&T Bank",
  "Marcus by Goldman Sachs",
  "Navy Federal Credit Union",
  "PNC Bank",
  "Regions Bank",
  "Santander Bank",
  "SoFi Bank",
  "Synchrony Bank",
  "TD Bank",
  "Truist Bank",
  "USAA Federal Savings Bank",
  "Varo Bank",
  "Wells Fargo Bank",
  "Zions Bank",
] as const;

export const currency = (n: number) =>
  n.toLocaleString("en-US", { style: "currency", currency: "USD" });
